### ISSUE TITLE
FastCraftPlus v0.18 generated an exception

### ISSUE THREAD

**Issue by buddhist09** [BenWoodworth/FastCraftPlus#39] opened 2016-04-21 14:29 UTC
# Description
FastCraftPlus v0.18 generated an exception

# Debug Output
<details><summary>Show **/fcadmin debug** output</summary>
```
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.18
  git-Spigot-5a40365-b103841 (MC: 1.9.2)
  1.9.2-R0.1-SNAPSHOT
  Java 1.8.0_65
Other Plugins (78):
  AreaShop 2.2.2
  AutoResponse 0.1.5
  AutoSaveWorld 4.15.dev
  BetterBanner 0.1.6
  Billboards 1.6
  Chairs 4.7
  ChestShop 4.0-r5
  ChunkSpawnerLimiter 3.0.4
  Citizens 2.0.17-SNAPSHOT (build 1357)
  ClearLag 2.9.0
  CompatNoCheatPlus 6.6.2-RC-sMD5NET-b83
  CoreProtect 2.12.0
  CraftBay 1.2.8
  CraftBook 3.9-SNAPSHOT
  CraftHeads 2.1.2
  CrateReloaded 1.3.26
  CustomHopper 1
  DropParty 3.1
  EnchantGUI 1.3.2
  EnjinMinecraftPlugin 3.0.14
  Essentials 2.0.1-b342
  EssentialsAntiBuild 2.0.1-b342
  EssentialsChat 2.0.1-b342
  EssentialsProtect 2.0.1-b342
  EssentialsSpawn 2.0.1-b342
  FarmAssist 2.2
  FeatherBoard 3.10.1
  FlashlightPlus 2.0
  GriefPrevention 14.5.1
  GroupManager 2.0.1-b332
  HideAndCustomPlugins 1.5.1
  HolographicDisplays 2.1.12
  icJukeBox 1.6.3
  IPWhitelist 1.6
  LegendaryMessages 6.0.3
  LibsDisguises 9.0.3
  Lockette 1.8.20
  Lottery 1.1.1
  MarriageMaster 1.29
  MicroJump 1.0.4
  MondoChest 0.7.2-pre1
  Multiverse-Core 2.5-b719
  Multiverse-Portals 2.5-b742
  MyCommand 5.2.5
  MyWarp 2.6.5
  NoCheatPlus 3.14.0-SNAPSHOT-sMD5NET-b960
  NoSpawnEggSpawners 1.0-SNAPSHOT
  PlayerVaults 3.5.8-SNAPSHOT-b195
  ProtocolLib 4.0.0-SNAPSHOT-b273
  RandomWarp 1.3
  Recipe_Changer 1.6
  Rlb 2.4
  Scavenger 1.7-9
  SecuritySystem 1.0
  ServerSigns 4.5.1
  Sign_Casino_Slots 1.5
  SignEdit 3.3.10
  SilkSpawners 3.7.2-SNAPSHOT-b335
  SimpleChatChannels 0.7.5
  SimpleSort 1.4
  SimpleVoteListener 2.6
  SkinsRestorer 11.4
  Smileychat 3.2
  SonarPet 1.0.1
  SpawnerShop 3.1
  SpecialHeads 4.0
  SuperCensor 2.8
  Sylvester 1.7.2
  TitleManager 1.5.11
  TrailGUI 5.0-b37-SNAPSHOT
  TreeAssist 5.10.1
  Vault 1.5.6-b49
  VoteParty 1.9.9.1
  Votifier 2.3.2.2
  WorldBorder 1.8.5
  WorldEdit 6.1.1-SNAPSHOT;3463-219d2da
  WorldGuard 6.1.2-SNAPSHOT;1653-65e48d1
  xPTradingCards 1
===========================================
```
</details>

# Stack Trace
<details><summary>Show stack trace</summary>
```
[14:12:41] [Server thread/WARN]: [FastCraftPlus] Task #1181372 for FastCraftPlus v0.18 generated an exception
java.lang.NullPointerException
	at co.kepler.fastcraftplus.config.LanguageConfig.gui_itemName(LanguageConfig.java:154) ~[?:?]
	at co.kepler.fastcraftplus.craftgui.GUIButtonRecipe.getItem(GUIButtonRecipe.java:54) ~[?:?]
	at co.kepler.fastcraftplus.api.gui.GUI.updateLayout(GUI.java:139) ~[?:?]
	at co.kepler.fastcraftplus.craftgui.GUIFastCraft.updateLayout(GUIFastCraft.java:212) ~[?:?]
	at co.kepler.fastcraftplus.craftgui.GUIFastCraft.inventoryChange(GUIFastCraft.java:295) ~[?:?]
	at co.kepler.fastcraftplus.craftgui.GUIFastCraft.access$1000(GUIFastCraft.java:29) ~[?:?]
	at co.kepler.fastcraftplus.craftgui.GUIFastCraft$GUIListener$1.run(GUIFastCraft.java:333) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-5a40365-b103841]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-5a40365-b103841]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-5a40365-b103841]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-5a40365-b103841]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_server.jar:git-Spigot-5a40365-b103841]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_server.jar:git-Spigot-5a40365-b103841]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```
</details>

**Comment by BenWoodworth** [comment] 2016-04-21 15:05
Can you provide the output when you run the command "fca debug" in the server console?

**Comment by buddhist09** [comment] 2016-04-21 15:15
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.18
  git-Spigot-5a40365-b103841 (MC: 1.9.2)
  1.9.2-R0.1-SNAPSHOT
  Java 1.8.0_65
Other Plugins (78):
  AreaShop 2.2.2
  AutoResponse 0.1.5
  AutoSaveWorld 4.15.dev
  BetterBanner 0.1.6
  Billboards 1.6
  Chairs 4.7
  ChestShop 4.0-r5
  ChunkSpawnerLimiter 3.0.4
  Citizens 2.0.17-SNAPSHOT (build 1357)
  ClearLag 2.9.0
  CompatNoCheatPlus 6.6.2-RC-sMD5NET-b83
  CoreProtect 2.12.0
  CraftBay 1.2.8
  CraftBook 3.9-SNAPSHOT
  CraftHeads 2.1.2
  CrateReloaded 1.3.26
  CustomHopper 1
  DropParty 3.1
  EnchantGUI 1.3.2
  EnjinMinecraftPlugin 3.0.14
  Essentials 2.0.1-b342
  EssentialsAntiBuild 2.0.1-b342
  EssentialsChat 2.0.1-b342
  EssentialsProtect 2.0.1-b342
  EssentialsSpawn 2.0.1-b342
  FarmAssist 2.2
  FeatherBoard 3.10.1
  FlashlightPlus 2.0
  GriefPrevention 14.5.1
  GroupManager 2.0.1-b332
  HideAndCustomPlugins 1.5.1
  HolographicDisplays 2.1.12
  icJukeBox 1.6.3
  IPWhitelist 1.6
  LegendaryMessages 6.0.3
  LibsDisguises 9.0.3
  Lockette 1.8.20
  Lottery 1.1.1
  MarriageMaster 1.29
  MicroJump 1.0.4
  MondoChest 0.7.2-pre1
  Multiverse-Core 2.5-b719
  Multiverse-Portals 2.5-b742
  MyCommand 5.2.5
  MyWarp 2.6.5
  NoCheatPlus 3.14.0-SNAPSHOT-sMD5NET-b960
  NoSpawnEggSpawners 1.0-SNAPSHOT
  PlayerVaults 3.5.8-SNAPSHOT-b195
  ProtocolLib 4.0.0-SNAPSHOT-b273
  RandomWarp 1.3
  Recipe_Changer 1.6
  Rlb 2.4
  Scavenger 1.7-9
  SecuritySystem 1.0
  ServerSigns 4.5.1
  Sign_Casino_Slots 1.5
  SignEdit 3.3.10
  SilkSpawners 3.7.2-SNAPSHOT-b335
  SimpleChatChannels 0.7.5
  SimpleSort 1.4
  SimpleVoteListener 2.6
  SkinsRestorer 11.4
  Smileychat 3.2
  SonarPet 1.0.1
  SpawnerShop 3.1
  SpecialHeads 4.0
  SuperCensor 2.8
  Sylvester 1.7.2
  TitleManager 1.5.11
  TrailGUI 5.0-b37-SNAPSHOT
  TreeAssist 5.10.1
  Vault 1.5.6-b49
  VoteParty 1.9.9.1
  Votifier 2.3.2.2
  WorldBorder 1.8.5
  WorldEdit 6.1.1-SNAPSHOT;3463-219d2da
  WorldGuard 6.1.2-SNAPSHOT;1653-65e48d1
  xPTradingCards 1
===========================================



Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by buddhist09** [comment] 2016-04-21 15:43
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.18
  git-Spigot-5a40365-b103841 (MC: 1.9.2)
  1.9.2-R0.1-SNAPSHOT
  Java 1.8.0_65
Other Plugins (78):
  AreaShop 2.2.2
  AutoResponse 0.1.5
  AutoSaveWorld 4.15.dev
  BetterBanner 0.1.6
  Billboards 1.6
  Chairs 4.7
  ChestShop 4.0-r5
  ChunkSpawnerLimiter 3.0.4
  Citizens 2.0.17-SNAPSHOT (build 1357)
  ClearLag 2.9.0
  CompatNoCheatPlus 6.6.2-RC-sMD5NET-b83
  CoreProtect 2.12.0
  CraftBay 1.2.8
  CraftBook 3.9-SNAPSHOT
  CraftHeads 2.1.2
  CrateReloaded 1.3.26
  CustomHopper 1
  DropParty 3.1
  EnchantGUI 1.3.2
  EnjinMinecraftPlugin 3.0.14
  Essentials 2.0.1-b342
  EssentialsAntiBuild 2.0.1-b342
  EssentialsChat 2.0.1-b342
  EssentialsProtect 2.0.1-b342
  EssentialsSpawn 2.0.1-b342
  FarmAssist 2.2
  FeatherBoard 3.10.1
  FlashlightPlus 2.0
  GriefPrevention 14.5.1
  GroupManager 2.0.1-b332
  HideAndCustomPlugins 1.5.1
  HolographicDisplays 2.1.12
  icJukeBox 1.6.3
  IPWhitelist 1.6
  LegendaryMessages 6.0.3
  LibsDisguises 9.0.3
  Lockette 1.8.20
  Lottery 1.1.1
  MarriageMaster 1.29
  MicroJump 1.0.4
  MondoChest 0.7.2-pre1
  Multiverse-Core 2.5-b719
  Multiverse-Portals 2.5-b742
  MyCommand 5.2.5
  MyWarp 2.6.5
  NoCheatPlus 3.14.0-SNAPSHOT-sMD5NET-b960
  NoSpawnEggSpawners 1.0-SNAPSHOT
  PlayerVaults 3.5.8-SNAPSHOT-b195
  ProtocolLib 4.0.0-SNAPSHOT-b273
  RandomWarp 1.3
  Recipe_Changer 1.6
  Rlb 2.4
  Scavenger 1.7-9
  SecuritySystem 1.0
  ServerSigns 4.5.1
  Sign_Casino_Slots 1.5
  SignEdit 3.3.10
  SilkSpawners 3.7.2-SNAPSHOT-b335
  SimpleChatChannels 0.7.5
  SimpleSort 1.4
  SimpleVoteListener 2.6
  SkinsRestorer 11.4
  Smileychat 3.2
  SonarPet 1.0.1
  SpawnerShop 3.1
  SpecialHeads 4.0
  SuperCensor 2.8
  Sylvester 1.7.2
  TitleManager 1.5.11
  TrailGUI 5.0-b37-SNAPSHOT
  TreeAssist 5.10.1
  Vault 1.5.6-b49
  VoteParty 1.9.9.1
  Votifier 2.3.2.2
  WorldBorder 1.8.5
  WorldEdit 6.1.1-SNAPSHOT;3463-219d2da
  WorldGuard 6.1.2-SNAPSHOT;1653-65e48d1
  xPTradingCards 1
===========================================

**Comment by BenWoodworth** [comment] 2016-05-09 17:23
Is this still an issue in the most recent update?

**Comment by BenWoodworth** [comment] 2016-05-20 07:18
I will close this, as I cannot reproduce it. If you are still having this error, please comment it.

**Closed by BenWoodworth** 2016-05-20 07:18 UTC
Labels: bug
